version: '3.1'

services:
  fastapi:
    build: ./fastapi
    restart: unless-stopped
    volumes:
       - ./model/:/model/
    ports:
      - 80:80
    environment:
      - MAX_WORKERS=3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
